const attributeNames = [
  ["Ryuichi-kai", "Torahide-gumi", "Nobu-rengo"],
  ["Blue", "Green", "Purple", "Red", "Blue", "Green", "Purple", "Red"],
  [
    "None",
    "Cross",
    "Diamond",
    "Helix",
    "Hoop",
    "Red Stud",
    "Bar",
    "Black Stud",
  ],
  [
    "None",
    "Jail Jumpsuit",
    "Jersey",
    "Kimono",
    "Kombini",
    "Leather Jacket",
    "Nanowave Jacket",
    "Neon Hoodie",
    "Rocker Jacket",
    "Sarashi",
    "School Uniform",
    "Shirt",
    "Suit With Scarf",
    "Suit",
    "Sukajan Nobu",
    "Sukajan Ryu",
    "Sukajan Tora",
    "Tactical Vest",
    "Tanktop",
    "Techwear Hoodie",
    "Techwear Kimono",
    "Techwear Turtleneck",
    "Training Suit",
    "Turtleneck Suit",
    "Varsity Jacket",
    "Akira",
    "Bartender",
    "Bloodstain Tanktop",
    "Body Suit",
    "Coat",
    "Cyborg",
    "Dress Shirt",
    "Fastfood Apron",
    "Fur Collar Jacket",
  ],
  [
    "None",
    "Halfmask Hannya",
    "Hannya Mask",
    "Jason Mask",
    "Led Mask",
    "Pipe Smoke",
    "Scar",
    "Skull Half Face",
    "Sun Glasses",
    "Tactical Mask",
    "Aviator Glasses",
    "Bandaid",
    "Bandana Mask",
    "Beard And Moustache",
    "Bloodstain",
    "Bubblegum",
    "Cigarette",
    "Cyclop Glasses",
    "Cyclop",
    "E-Smoker",
    "Eye Patch",
    "Eyes",
    "Gasmask",
    "Glasses",
  ],
  [
    "None",
    "Cowboy Hat",
    "Crew Cut",
    "Curtain Platinum",
    "Curtain",
    "Cyber Jingasan",
    "Faux Hawk Red",
    "Flatcap",
    "Gentelman Hat",
    "Jojo Cap",
    "Mullet Kinpatsu",
    "Mullet",
    "Pompadour",
    "Punchperm",
    "Punk Cap",
    "Punk",
    "Skate Helmet",
    "Skinhead",
    "Slick Curtain",
    "Slick Curtain",
    "Snapback",
    "Spiky Blue",
    "Suave Cut",
    "Suave Undercut Red",
    "Suave Undercut",
    "Swept Back",
    "Techcap",
    "Trucker Cap",
    "Twisted Hachimaki",
    "Undercut Dredlock",
    "Undercut Dredlock Green",
    "Undercut Green",
    "Undercut",
    "Ushanka",
    "Visor Cap",
    "Zero Hachimaki",
    "Akira",
    "Bandana",
    "Banie",
    "Baseball Cap",
    "Bowlcut",
    "Braided Ombre",
    "Braided",
    "Buckethat",
    "Bun",
    "Buzz Cut Kinpatsu",
    "Buzz Cut",
    "Buzz Mohawk",
    "Chonmage",
    "Conical Hat",
  ],
  ["None", "Jaw Half Neck", "Neck", "Cyber 1", "Cyber 2"],
];
module.exports = attributeNames;
